### ISSUE TITLE
Login Error - Unfortunately, swe574.boun.edu.androidproject has stopped.

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#33]
When I try to run the mobile application via Android Studio, the application crashes just as the Login screen is opened.

User name: thomas@anderson.com
Password: thomas123

![image](https://cloud.githubusercontent.com/assets/4705964/11919343/c79ccb84-a758-11e5-83b7-f120919342e5.png)

12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime: Process: swe574.boun.edu.androidproject, PID: 881
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:300)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:  Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Date
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at swe574.boun.edu.androidproject.model.User.createFromJSON(User.java:96)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at swe574.boun.edu.androidproject.tasks.QuerySelfTask.doInBackground(QuerySelfTask.java:83)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at swe574.boun.edu.androidproject.tasks.QuerySelfTask.doInBackground(QuerySelfTask.java:27)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
12-20 13:23:12.060 881-943/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)

**Comment by cakyel** [comment]
## Test Cases

> **GIVEN** there is an existing user,
> **WHEN** the user open mobile application,
> **THEN** login screen should be loaded correctly
- [x] Mobile application loaded without a crash
- [x] Login credentials can be filled 
- [x] Login successful

**Comment by cakyel** [comment]
Tested OK
