### ISSUE TITLE
Update Group Screen - Application has stopped when a recommended tag is selected

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#70]
When I try to select a recommended tag in Update Group screen, application stops.

User: amy@winehouse.com
Pass: amy123
Group: Amsterdam Lovers

![image](https://cloud.githubusercontent.com/assets/4705964/12076549/080337ac-b1b9-11e5-9482-f51b72562fa7.png)

Logcat:

01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime: FATAL EXCEPTION: main
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime: Process: swe574.boun.edu.androidproject, PID: 868
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime: java.lang.NullPointerException: println needs a message
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.util.Log.println_native(Native Method)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.util.Log.v(Log.java:118)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at swe574.boun.edu.androidproject.UpdateGroupActivity$3.onItemClick(UpdateGroupActivity.java:195)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:902)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.widget.AutoCompleteTextView.access$500(AutoCompleteTextView.java:91)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1192)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.widget.AdapterView.performItemClick(AdapterView.java:299)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.widget.AbsListView$3.run(AbsListView.java:3645)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
01-02 18:26:14.181 868-868/swe574.boun.edu.androidproject E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

Extra info: After this error is occured, I try again to enter a tag but I get another error this time. So I have to restart the application in order to get the first error.

Logcat:

01-02 18:28:03.941 2608-3302/swe574.boun.edu.androidproject E/Volley: [87] BasicNetwork.performRequest: Unexpected response code 500 for http://162.243.18.170:9000/v1/semantic/queryLabel
01-02 18:28:03.961 2608-2608/swe574.boun.edu.androidproject E/ERROR: com.android.volley.ServerError
01-02 18:28:04.021 2608-3301/swe574.boun.edu.androidproject D/dalvikvm: GC_FOR_ALLOC freed 305K, 8% free 4960K/5336K, paused 27ms, total 27ms
01-02 18:28:04.461 2608-3302/swe574.boun.edu.androidproject E/Volley: [87] BasicNetwork.performRequest: Unexpected response code 500 for http://162.243.18.170:9000/v1/semantic/queryLabel
01-02 18:28:04.461 2608-2608/swe574.boun.edu.androidproject E/ERROR: com.android.volley.ServerError
01-02 18:28:04.861 2608-3302/swe574.boun.edu.androidproject E/Volley: [87] BasicNetwork.performRequest: Unexpected response code 500 for http://162.243.18.170:9000/v1/semantic/queryLabel
01-02 18:28:04.871 2608-2608/swe574.boun.edu.androidproject E/ERROR: com.android.volley.ServerError

**Comment by cakyel** [comment]
Extra information: I did not get this error on New Note screen:

![image](https://cloud.githubusercontent.com/assets/4705964/12076659/f5b60346-b1bc-11e5-8bf8-d9ddb7eb049e.png)
